/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        mantis: {
          50: 'rgb(var(--color-mantis-50) / <alpha-value>)',
          100: 'rgb(var(--color-mantis-100) / <alpha-value>)',
          200: 'rgb(var(--color-mantis-200) / <alpha-value>)',
          300: 'rgb(var(--color-mantis-300) / <alpha-value>)',
          400: 'rgb(var(--color-mantis-400) / <alpha-value>)',
          500: 'rgb(var(--color-mantis-500) / <alpha-value>)',
          600: 'rgb(var(--color-mantis-600) / <alpha-value>)',
          700: 'rgb(var(--color-mantis-700) / <alpha-value>)',
          800: 'rgb(var(--color-mantis-800) / <alpha-value>)',
          900: 'rgb(var(--color-mantis-900) / <alpha-value>)',
          950: 'rgb(var(--color-mantis-950) / <alpha-value>)',
        },
        main: 'var(--text-main)',
        bgmain: 'var(--bg-main)',
        slate: {
          50: 'rgb(var(--color-slate-50) / <alpha-value>)',
          100: 'rgb(var(--color-slate-100) / <alpha-value>)',
          200: 'rgb(var(--color-slate-200) / <alpha-value>)',
          300: 'rgb(var(--color-slate-300) / <alpha-value>)',
          400: 'rgb(var(--color-slate-400) / <alpha-value>)',
          500: 'rgb(var(--color-slate-500) / <alpha-value>)',
          600: 'rgb(var(--color-slate-600) / <alpha-value>)',
          700: 'rgb(var(--color-slate-700) / <alpha-value>)',
          800: 'rgb(var(--color-slate-800) / <alpha-value>)',
          900: 'rgb(var(--color-slate-900) / <alpha-value>)',
          950: 'rgb(var(--color-slate-950) / <alpha-value>)',
          850: 'rgb(var(--color-slate-850) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--color-indigo-50) / <alpha-value>)',
          100: 'rgb(var(--color-indigo-100) / <alpha-value>)',
          200: 'rgb(var(--color-indigo-200) / <alpha-value>)',
          300: 'rgb(var(--color-indigo-300) / <alpha-value>)',
          400: 'rgb(var(--color-indigo-400) / <alpha-value>)',
          500: 'rgb(var(--color-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--color-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--color-indigo-700) / <alpha-value>)',
          800: 'rgb(var(--color-indigo-800) / <alpha-value>)',
          900: 'rgb(var(--color-indigo-900) / <alpha-value>)',
          950: 'rgb(var(--color-indigo-950) / <alpha-value>)',
        },
        rose: {
          50: 'rgb(var(--color-rose-50) / <alpha-value>)',
          100: 'rgb(var(--color-rose-100) / <alpha-value>)',
          200: 'rgb(var(--color-rose-200) / <alpha-value>)',
          300: 'rgb(var(--color-rose-300) / <alpha-value>)',
          400: 'rgb(var(--color-rose-400) / <alpha-value>)',
          500: 'rgb(var(--color-rose-500) / <alpha-value>)',
          600: 'rgb(var(--color-rose-600) / <alpha-value>)',
          700: 'rgb(var(--color-rose-700) / <alpha-value>)',
          800: 'rgb(var(--color-rose-800) / <alpha-value>)',
          900: 'rgb(var(--color-rose-900) / <alpha-value>)',
          950: 'rgb(var(--color-rose-950) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--color-amber-50) / <alpha-value>)',
          100: 'rgb(var(--color-amber-100) / <alpha-value>)',
          200: 'rgb(var(--color-amber-200) / <alpha-value>)',
          300: 'rgb(var(--color-amber-300) / <alpha-value>)',
          400: 'rgb(var(--color-amber-400) / <alpha-value>)',
          500: 'rgb(var(--color-amber-500) / <alpha-value>)',
          600: 'rgb(var(--color-amber-600) / <alpha-value>)',
          700: 'rgb(var(--color-amber-700) / <alpha-value>)',
          800: 'rgb(var(--color-amber-800) / <alpha-value>)',
          900: 'rgb(var(--color-amber-900) / <alpha-value>)',
          950: 'rgb(var(--color-amber-950) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--color-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--color-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--color-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--color-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--color-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--color-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--color-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--color-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--color-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--color-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--color-emerald-950) / <alpha-value>)',
        },
        teal: {
          50: 'rgb(var(--color-teal-50) / <alpha-value>)',
          100: 'rgb(var(--color-teal-100) / <alpha-value>)',
          200: 'rgb(var(--color-teal-200) / <alpha-value>)',
          300: 'rgb(var(--color-teal-300) / <alpha-value>)',
          400: 'rgb(var(--color-teal-400) / <alpha-value>)',
          500: 'rgb(var(--color-teal-500) / <alpha-value>)',
          600: 'rgb(var(--color-teal-600) / <alpha-value>)',
          700: 'rgb(var(--color-teal-700) / <alpha-value>)',
          800: 'rgb(var(--color-teal-800) / <alpha-value>)',
          900: 'rgb(var(--color-teal-900) / <alpha-value>)',
          950: 'rgb(var(--color-teal-950) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--color-blue-50) / <alpha-value>)',
          100: 'rgb(var(--color-blue-100) / <alpha-value>)',
          200: 'rgb(var(--color-blue-200) / <alpha-value>)',
          300: 'rgb(var(--color-blue-300) / <alpha-value>)',
          400: 'rgb(var(--color-blue-400) / <alpha-value>)',
          500: 'rgb(var(--color-blue-500) / <alpha-value>)',
          600: 'rgb(var(--color-blue-600) / <alpha-value>)',
          700: 'rgb(var(--color-blue-700) / <alpha-value>)',
          800: 'rgb(var(--color-blue-800) / <alpha-value>)',
          900: 'rgb(var(--color-blue-900) / <alpha-value>)',
          950: 'rgb(var(--color-blue-950) / <alpha-value>)',
        },
        red: {
          50: 'rgb(var(--color-red-50) / <alpha-value>)',
          100: 'rgb(var(--color-red-100) / <alpha-value>)',
          200: 'rgb(var(--color-red-200) / <alpha-value>)',
          300: 'rgb(var(--color-red-300) / <alpha-value>)',
          400: 'rgb(var(--color-red-400) / <alpha-value>)',
          500: 'rgb(var(--color-red-500) / <alpha-value>)',
          600: 'rgb(var(--color-red-600) / <alpha-value>)',
          700: 'rgb(var(--color-red-700) / <alpha-value>)',
          800: 'rgb(var(--color-red-800) / <alpha-value>)',
          900: 'rgb(var(--color-red-900) / <alpha-value>)',
          950: 'rgb(var(--color-red-950) / <alpha-value>)',
        },
        gray: {
          50: 'rgb(var(--color-gray-50) / <alpha-value>)',
          100: 'rgb(var(--color-gray-100) / <alpha-value>)',
          200: 'rgb(var(--color-gray-200) / <alpha-value>)',
          300: 'rgb(var(--color-gray-300) / <alpha-value>)',
          400: 'rgb(var(--color-gray-400) / <alpha-value>)',
          500: 'rgb(var(--color-gray-500) / <alpha-value>)',
          600: 'rgb(var(--color-gray-600) / <alpha-value>)',
          700: 'rgb(var(--color-gray-700) / <alpha-value>)',
          800: 'rgb(var(--color-gray-800) / <alpha-value>)',
          900: 'rgb(var(--color-gray-900) / <alpha-value>)',
          950: 'rgb(var(--color-gray-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Menlo', 'Consolas', 'monospace'],
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
